name: aicaremanagermob
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  lucide_icons: ^0.257.0
  flutter_svg: ^2.1.0
  provider: ^6.1.1
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.6.1
  amplify_flutter: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_authenticator: ^2.3.3
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.5
  intl: ^0.19.0
  web_socket_channel: ^2.4.0
  dash_chat_2: ^0.0.8
  font_awesome_flutter: ^10.7.0
  socket_io_client: ^2.0.3+1
  cached_network_image: ^3.3.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  fluttertoast: ^8.2.12
  freezed_annotation: ^3.0.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  printing: ^5.11.1
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
